Public Partial Class Twitter
'    このファイルはデバッグビルドのTweenにより自動作成されました   作成日時  2008/10/18 2:06:36

    Private _splitPost As String = "<tr id=""status_"
    Private _splitPostRecent As String = "<tr id=""status_"
    Private _statusIdTo As String = """"
    Private _splitDM As String = "<tr id=""status_"
    Private _parseName As String = "://twitter.com/"
    Private _parseNameTo As String = """"
    Private _parseNick As String = "<img alt="""
    Private _parseNickTo As String = """"
    Private  _parseImg As String = "src="""
    Private _parseImgTo As String = """"
    Private _parseMsg1 As String = "<span class=""entry-content"">"
    Private _parseMsg2 As String = "</span>"
    Private _parseDM1 As String = "<span class=""entry-content"">"
    Private _parseDM2 As String = "</span>"
    Private _parseDate As String = "<span class=""published"" title="""
    Private _parseDateTo As String = """"
    Private _getAuthKey As String = "<input name=""authenticity_token"" value="""
    Private _getAuthKeyTo As String = """"
    Private _parseStar As String = "<a href=""#"" class="""
    Private _parseStarTo As String = """"
    Private _parseStarEmpty As String = "non-fav"
    Private _followerList As String = "<select id=""direct_message_user_id"" name=""user[id]""><option value="""" selected=""selected"">"
    Private _followerMbr1 As String = "/option>"
    Private _followerMbr2 As String = """>"
    Private _followerMbr3 As String = "<"
    Private _getInfoTwitter As String = "<div id=""top_alert"">"
    Private _getInfoTwitterTo As String = "</div>"
    Private _isProtect As String = "<img alt=""Icon_red_lock"""
    Private _isReplyEng As String = ">in reply to "
    Private _isReplyJpn As String = ">u8fd4u4fe1: "
    Private _isReplyTo As String = "<"
    Private _parseProtectMsg1 As String = "."" />"
    Private _parseProtectMsg2 As String = "<span class=""meta entry-meta"">"
    Private _parseDMCount1 As String = "<a href=""/direct_messages"" id=""direct_messages_tab""><span id=""message_count"" class=""stat_count"">"
    Private _parseDMCount2 As String = "</span>"
End Class
