'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3053
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tween.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property At() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("At", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property AtBlink() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AtBlink", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property AtRed() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AtRed", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property AtSmoke() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AtSmoke", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  実行形式ファイル(*.exe)|*.exe|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Button3_ClickText1() As String
            Get
                Return ResourceManager.GetString("Button3_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ブラウザを指定してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Button3_ClickText2() As String
            Get
                Return ResourceManager.GetString("Button3_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新履歴
        '''
        '''***Ver0.1.6.1(Unreleased)
        '''-コマンド回避ロジックを調整
        '''***Ver0.1.6.0(2008/11/28)
        '''-詳細発言表示部分からの右クリック検索をローカライズ対応可能にした。その他メニュー項目の見直しを行った。
        '''-初期化完了してからフォームを表示するようにした（つもり）
        '''-詳細発言表示部分からの右クリックメニューでURLをコピーできるようにした
        '''-詳細発言表示部分からの検索の際に文字列を正規化していなかったのを修正
        '''-文字列を選択していなかったときに検索をしようとした場合の動作を修正
        '''-詳細発言表示部分からの右クリックメニューで、選択文字列を現在のタブで検索できるようにした。
        '''-Twitterコマンド誤認問題が本家で修正されたのにあわせ、回避ロジック修正
        '''-HTML解析に失敗したとき、切り出したHTMLをファイル出力（コマンドライン引数&apos;/d&apos;の時のみ）
        '''-DMが取れないケースに対応
        '''***Ver0.1.5.0(2008/11/25)
        '''-アイコンサイズ48*48の1列表示が正常に表示されないバグ修正
        '''***Ver0.1.4.0(2008/ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ChangeLog() As String
            Get
                Return ResourceManager.GetString("ChangeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新間隔には数値（0または15～600）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DMPeriod_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("DMPeriod_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新間隔には数値（0または15～600）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DMPeriod_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("DMPeriod_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  この設定ファイルは Tween により自動生成されました。手動で変更しないでください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LoadConfigurationText1() As String
            Get
                Return ResourceManager.GetString("LoadConfigurationText1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property MIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  ページ数には数値（1～20）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NextPages_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("NextPages_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ページ数には数値（1～20）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NextPages_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("NextPages_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  閾値には数値（1～20）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NextThreshold_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("NextThreshold_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  閾値には数値（1～20）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NextThreshold_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("NextThreshold_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh4() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh4", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ReplyBlink() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ReplyBlink", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Repry() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Repry", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  ユーザー名とパスワードを指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Save_ClickText1() As String
            Get
                Return ResourceManager.GetString("Save_ClickText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ユーザー名に『@』を含めないでください。（メールアドレス不可） に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Save_ClickText2() As String
            Get
                Return ResourceManager.GetString("Save_ClickText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  設定値に誤りがあります。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Save_ClickText3() As String
            Get
                Return ResourceManager.GetString("Save_ClickText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://en.wikipedia.org/wiki/{0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SearchItem1Url() As String
            Get
                Return ResourceManager.GetString("SearchItem1Url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://www.google.com/search?q={0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SearchItem2Url() As String
            Get
                Return ResourceManager.GetString("SearchItem2Url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://pcod.no-ip.org/yats/search?query={0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SearchItem3Url() As String
            Get
                Return ResourceManager.GetString("SearchItem3Url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://search.twitter.com/search?q=&amp;amp;ands={0}&amp;amp;phrase=&amp;amp;ors=&amp;amp;nots=&amp;amp;tag=&amp;amp;lang=en&amp;amp;from=&amp;amp;to=&amp;amp;ref=&amp;amp;near=&amp;amp;within=15&amp;amp;units=mi&amp;amp;since=&amp;amp;until=&amp;amp;rpp=15 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SearchItem4Url() As String
            Get
                Return ResourceManager.GetString("SearchItem4Url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（1～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadDM_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("StartupReadDM_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（1～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadDM_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("StartupReadDM_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（1～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadPages_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("StartupReadPages_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（1～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadPages_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("StartupReadPages_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（0～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadReply_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("StartupReadReply_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み込みページ数には数値（0～999）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupReadReply_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("StartupReadReply_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Tweenは既に起動されています。2重起動する場合は、別フォルダのTween.exeを実行してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupText1() As String
            Get
                Return ResourceManager.GetString("StartupText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Tween二重起動チェック に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartupText2() As String
            Get
                Return ResourceManager.GetString("StartupText2", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property TabIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TabIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  ポート番号には整数値を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TextProxyPort_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("TextProxyPort_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ポート番号には0～65535を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TextProxyPort_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("TextProxyPort_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新間隔には数値（0または15～600）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TimelinePeriod_ValidatingText1() As String
            Get
                Return ResourceManager.GetString("TimelinePeriod_ValidatingText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新間隔には数値（0または15～600）を指定してください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TimelinePeriod_ValidatingText2() As String
            Get
                Return ResourceManager.GetString("TimelinePeriod_ValidatingText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  **** エラー ログ: {0} **** に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText1() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  エラー発生 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText10() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  このファイルの内容を kiri.feather@gmail.com まで送っていただけると助かります。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText2() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ご面倒なら@kiri_featherまでお知らせ頂くだけでも助かります。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText3() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  動作環境: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText4() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  オペレーティング システム: {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText5() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  共通言語ランタイム       : {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText6() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Tween.exeのバージョン    : {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText7() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  例外 {0}: {1} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText8() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  エラーが発生しました。ごめんなさい。ログをexeファイルのある場所に {0} として作ったので、kiri.feather@gmail.comまで送っていただけると助かります。{1}ご面倒なら@kiri_featherまでお知らせ頂くだけでも助かります。{1}「OK」ボタンをクリックするとログを開きます。ログを開かない場合は「キャンセル」ボタンをクリックしてください。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionText9() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionText9", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
